---
- name: restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart apt-daily.timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
