---
- name: System upgrade tasks
  import_tasks: system_upgrade.yml

- name: Journald configuration tasks
  import_tasks: journald.yml

- name: Unattended upgrades tasks
  import_tasks: unattended_upgrades.yml

- name: APT daily timer tasks
  import_tasks: apt_daily_timer.yml
